---
- name: Install filebeat
  hosts: web
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install gnupg, apt-transport-https
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Copy filebeat 7.14.1
      copy:
        src: /home/prokhorov/terraform/ansible/filebeat-7.14.1-amd64.deb
        dest: /home/prokhorov/

    - name: Install filebeat
      apt:
        deb: /home/prokhorov/filebeat-7.14.1-amd64.deb

    - name: Copy config file for filebeat
      copy:
        src: /home/prokhorov/terraform/filebeat.yml
        dest: /etc/filebeat
        mode: 0600
        owner: root
        group: root

    - name: Systemctl daemon reload
      systemd:
        daemon_reload: true
        name: filebeat.service
        state: started
