---
- name: Install Zabbix agent
  hosts: web
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name: ["zabbix-agent"]
        state: present

    - name: Copy Zabbix Agent configuration file
      copy:
        src: /home/prokhorov/terraform/ansible/zabbix_agent.conf
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: "0644"

    - name: Start and enable Zabbix Agent service
      service:
        name: zabbix-agent
        state: started
        enabled: yes
